### ISSUE TITLE
Migration error when migration entry has "on_delete: :nullify"

### ISSUE THREAD

**Issue by jmufugi** [luckyframework/lucky_migrator#111]
I am getting error when migration entry has "on_delete: :nullify"
"Unexpected error while running migrations: syntax error at or near "NULLIFY"
Seems :nullify is not converted to sql "SET NULL" "
Bug in lucky_migrator.

**Comment by paulcsmith** [comment]
Closed by https://github.com/luckyframework/lucky_migrator/pull/117#pullrequestreview-136754540
