### ISSUE TITLE
bin/gen.migration is included in the source repo

### ISSUE THREAD

**Issue by lee-b** [luckyframework/lucky_migrator#128]
Binaries shouldn't be included in the source repo.  For one reason, the binary in question is for a specific platform.  For another, it's huge, and probably makes the repo cloning take a LOT longer.  But it's also just not the done thing, for many reasons.

**Comment by paulcsmith** [comment]
You are right. This was accidentally committed. If you'd like, could you submit a PR removing it and adding it to .gitignore?

**Comment by paulcsmith** [comment]
Closed by https://github.com/luckyframework/lucky_migrator/pull/129
