### ISSUE TITLE
Add `make_optional` and `make_required`

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_migrator#50]
Inspired by https://github.com/luckyframework/lucky_migrator/issues/12#issuecomment-348528866

`make_required :table_name, :column_name` -> `execute "ALTER TABLE table_name ALTER COLUMN column_name SET NOT NULL;"`

`make_optional :table_name, :column_name` -> `execute "ALTER TABLE table_name ALTER COLUMN column_name DROP NOT NULL;"`

*Note* I didn't check the SQL so it may require small changes

Also, thoughts on the name? I think "required" and "optional" make more sense than "NOT NULL", but maybe not worth breaking the established terms?

**Comment by edwardloveall** [comment]
Love the idea.

I guess the names at the opposite end of the spectrum would be `set_not_null` and `drop_not_null` which isn't great. I like your names better.

**Comment by mikeeus** [comment]
Would these methods go in `LuckyMigrator::StatementHelpers` like `create_index` to be used in the `migrate` method?

And if so, should I make a class like `AlterColumnStatement` to handle these?

**Comment by paulcsmith** [comment]
Yes I think they should go in `LuckyMigrator::StatementHelpers` and I think a class could be good. maybe `ChangeNullStatement`?

**Comment by mikeeus** [comment]
Sounds good, I'll make a PR

**Comment by mikeeus** [comment]
K the PR is up :)
