### ISSUE TITLE
Raise helpful message if you try to generate a migration with _

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/lucky_migrator#63]
So if you do `lucky gen.migration create_users` it would say: `must use a class name like: lucky gen.migration CreateUsers`

**Comment by mikeeus** [comment]
Is there a reason why we convert `create_users` to `CreateUsers` automatically?

**Comment by paulcsmith** [comment]
We could definitely do that, but then there would be two ways people could use things. That isn't so bad, but it leads to other things that are a bit worse. You'll see people writing blogs where some use snakecase and other's camel case, people will wonder if there is a difference between the two, and it is also one more layer of thinking.

So I think raising so that there is on way to create a migration will help the community out.

**Comment by mikeeus** [comment]
K I get that, thanks
